### ISSUE TITLE
Public API key

### ISSUE THREAD

**Issue by Hyperson** [piashcse/Hilt-MVVM-Compose-Movie#2]
Hi, 

First of all, I would like to say nice work ! :)

I suggest you remove your API key inside `ApiURL `. It is really a bad practice ;)

**Comment by piashcse** [comment]
I intentionally make it public so that folks don't have to do extra effort for generating API key from TMDB

**Comment by piashcse** [comment]
Added as build config 
Ref:
https://github.com/piashcse/Hilt-MVVM-Compose-Movie/pull/6
